//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public string Book_ID { get; set; }
        public string Language { get; set; }
        public string Title { get; set; }
        public string Category { get; set; }
        public string Edition { get; set; }
        public string ISBN { get; set; }
        public string DDC_No { get; set; }
        public string Author { get; set; }
        public string Publisher { get; set; }
        public string Publication_Date { get; set; }
        public string Attachment { get; set; }
        public string Price { get; set; }
        public string Recieved_By { get; set; }
        public string Other_Details { get; set; }
        public string Reference { get; set; }
        public string Availability { get; set; }
    }
}
