//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Borrow
    {
        public string Book_ID { get; set; }
        public string Member_ID { get; set; }
        public System.DateTime Issu_Date { get; set; }
        public System.DateTime Due_Date { get; set; }
        public string Contact_NO { get; set; }
        public string Email { get; set; }
        public string Member_Type { get; set; }
    }
}
