//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Library_Management_SystemEntities : DbContext
    {
        public Library_Management_SystemEntities()
            : base("name=Library_Management_SystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Borrow> Borrows { get; set; }
        public DbSet<Student_Member> Student_Member { get; set; }
        public DbSet<Staff_Member> Staff_Member { get; set; }
        public DbSet<Book> Books { get; set; }
    }
}
