//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff_Member
    {
        public string Member_ID { get; set; }
        public string Name { get; set; }
        public string NIC { get; set; }
        public string Gender { get; set; }
        public string Contact_NO { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Academic_Non_Academic { get; set; }
        public string Permenent_Visiting { get; set; }
    }
}
